---
# Tasks for installing latest version of Docker-Engine on each node

- name: Run apt-get update
  apt: update_cache=yes

- name: Install "apt-transport-https"
  apt: name=apt-transport-https state=present

- name: Install "ca-certificates"
  apt: name=ca-certificates state=present

#- name: Add new GPG key
#  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

#- name: Add new GPG key
#  get_url: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xF76221572C52609D dest=/tmp/key.txt use_proxy=yes mode=777

#- name: Add new GPG key
#  command: curl http://keyserver.ubuntu.com/pks/lookup\?op\=get\&fingerprint\=on\&search\=0xF76221572C52609D -o "key.txt"

- name: Create Repo-file in /etc/apt
  file: path=/etc/apt/sources.list.d/docker.list state=touch

- name: Modify Repo-file
  lineinfile:
   dest: /etc/apt/sources.list.d/docker.list
   state: present
   regexp: "{{ item.regexp }}"
   line: "{{ item.line}}"
  with_items:
   - { regexp: 'deb',  line: '{{repo}}' }

#- name: Update source-list in /etc/apt
#  apt_repository: repo='{{repo}}'  filename='docker' state=present

- name: Run apt-get update again
  apt: update_cache=yes

- name: purge lxc-docker
  apt: name=lxc-docker state=absent purge=yes

- name: Install Docker-Engine
  apt: name=docker-engine state=latest
